### ISSUE TITLE
exec could not launch process: no such file or directory

### ISSUE THREAD

**Issue by downey** [go-delve/delve#1611]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
1.2.0
2. What version of Go are you using? (`go version`)?
1.12.7 linux/amd64
3. What operating system and processor architecture are you using?
mac x86_64 running Docker using the golang:1.12 image (Debian GNU/Linux 9 (stretch)) x86_64
4. What did you do?
from Docker:
`dlv --listen=:58257 --headless=true --api-version=2 exec /go/bin/apollo -- integ/temp.json`
Here's the fuller setup:
docker-compose.yml
```
services:
  service:
    build: .
    ports:
      - '8106:8106'
      - '58257:58257'
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
```
Dockerfile
```
FROM golang:1.11.2

WORKDIR /go/src/cdowney/go/apollo
COPY . .

RUN go install -v -gcflags "all=-N -l" cdowney/go/apollo/cmd/apollo

RUN chmod +x integ/entrypoint.sh \
    && go get github.com/derekparker/delve/cmd/dlv

CMD ["integ/entrypoint.sh"]
```
entrypoint.sh
```
#!/usr/bin/env bash
dlv --listen=:58257 --headless=true --api-version=2 exec apollo -- integ/config.json
```

5. What did you expect to see?
```
API server listening at: 127.0.0.1:58257
Listening on port 8106...
```

6. What did you see instead?
```
API server listening at: 127.0.0.1:58257
could not launch process: open apollo: no such file or directory
Listening on port 8106...
```
