### ISSUE TITLE
Debugging in container/k8 slow

### ISSUE THREAD

**Issue by danielfoehrKn** [go-delve/delve#1741]
1. What version of Delve are you using (`dlv version`)?
1.3.2
2. What version of Go are you using? (`go version`)?
go1.13.1 darwin/amd64
3. What operating system and processor architecture are you using?
OsX Mojave 10.14.6
4. What did you do?

I set up delve to debug a golang app in a container running a Kubernetes cluster (tested both local and remote using port-forward).
The attaching to the delv debug server via Intellij works. The program starts executing in the expected fashion and eventually runs into my breakpoints.
 However it is extremely slow - talking 2 minutes to even see the first log outputs and 10 minutes to reach a breakpoint somewhere during execution.

Using delve via intellij Goland to attach to go application running locally works smooth.

- Is this the expected behaviour? 
- Should I execute delve in a different way (e.g start program first and then use attach)?
 - Is there a way to speed up program execution?

------

Kind of application:
- Kubernetes operator using controller-runtime.

Application is being build via:

.PHONY: build-debug
build-debug:
	@CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build \
		-mod=vendor \
		-gcflags "all=-N -l" \
		-o ./bin/gardener-xxx-debug \
		cmd/*.go

Dockerfile:

```
...
FROM golang:1.12.8 AS builder-base
...
# Download the dlv (delve) debugger for go (you can comment this out if unused)
RUN go get -u -v github.com/go-delve/delve/cmd/dlv
RUN apk add --update bash curl
RUN apk add --no-cache libc6-compat
..
COPY --from=builder /go/src/xxx/kubernetes/gardener-xxxx/bin/gardener-xxx-debug /usr/local/bin
COPY --from=builder /go/bin/dlv /usr/local/bin
COPY --from=builder /go/src/xxx/kubernetes/gardener-xxx/entrypoint.sh /
RUN chmod +x /entrypoint.sh
```
This is the Kubernetes deployment:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gardener-deployxxx
  namespace: default
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
  template:
    metadata:
    spec:
      serviceAccountName: gardener-xxx
      containers:
      - name: gardener-xxx
        image: my_docker_image
        imagePullPolicy: Always
        command:
        - /entrypoint.sh
        args:
        - arg_needed
        volumeMounts:
        - name: config
          mountPath: /etc/xxx/config
        securityContext:
          capabilities:
            add:
              - SYS_PTRACE
        ports:
        - containerPort: 3000
          name: debug
          protocol: TCP
      volumes:
        - name: config
          configMap:
            name: xxx
            defaultMode: 420
```
The Entrypoint skript then calls dlv in the container with

```
/usr/local/bin/dlv --continue --listen=:3000 --headless=true --api-version=2 --accept-multiclient exec /usr/local/bin/gardener-xxx -- --config-file=/etc/${CONFIG_PATH}/config/config.yaml
```

5. What did you expect to see?
Application being started by dlv to execute quicker.
6. What did you see instead?
Program execution is too slow to be usable. http connections being dropped via timeouts etc. 

Thank you very much.
