### ISSUE TITLE
API server started listening and exiting out immediately in windows

### ISSUE THREAD

**Issue by Arunkayathi** [go-delve/delve#1898]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

**Delve Debugger
Version: 1.3.2
Build: $Id: 569ccbd514fc47c8b4c521b142556867ec5e6917 $**

2. What version of Go are you using? (`go version`)?
**go version go1.13.7** 

3. What operating system and processor architecture are you using?
**windows/amd64**

4. What did you do?
**I am trying to debug a go application running inside a container**

5. What did you expect to see?
**Able to start debugging the application**

6. What did you see instead?
**Server started and exiting out immediately as soon as I expose a port for dlv**

Docker file

```
FROM golang:1.12

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

RUN go get github.com/go-delve/delve/cmd/dlv

# set the working directory to /go/src
WORKDIR $GOPATH/src

# Copy everything from the current directory to the working directory inside the container
# (as set by WORKDIR)
COPY . .

# 8080 is for the web application
EXPOSE 8080 2345
```

docker-compose.yml

version: "3.0"

```
services:
  web:
    container_name: go-delve-docker-example
    build: "./"
    ports:
      - "8080:8080"
      - "2345:2345"
    security_opt:
      - "seccomp:unconfined"
    tty: true
    stdin_open: true
    command: dlv debug --headless --listen=0.0.0.0:2345 --api-version=2 --log main.go
```

Output

```
go-delve-docker-example | API server listening at: [::]:2345
go-delve-docker-example | 2020-02-27T17:56:35Z info layer=debugger launching process with args: [/go/src/__debug_bin]
go-delve-docker-example | 2020-02-27T17:56:36Z error layer=rpc rpc:invalid character 'H' looking for beginning of value
go-delve-docker-example exited with code 0
```
