### ISSUE TITLE
How do I install the tool needed for dlv-dap so that VS Code can debug without having to click on the popup?

### ISSUE THREAD

**Issue by mattwelke** [go-delve/delve#2808]
**Background:**

Gitpod is a cloud-based remote development environment. You make "workspaces" for your repos where a workspace is an ephemeral container that you connect to via web browser to get a VS Code-like environment. It uses the VS Code project behind the scenes to power the editor you get in the web browser.

You use a file called `.gitpod.yml` to configure the extensions you want it to pre-install for you, and to configure the "init" task which it will run as it creates a workspace to make sure that when it loads, you're ready to code.

**Problem:**

I can't get a Gitpod workspace to work with the debugger out of the box. I tried adding a step to my init task to get the dlv-dap tool installed, but it doesn't appear to work. I'd like to know what command to add to my init task so that my workspace has dlv-dap ready to go as it loads in my web browser.

Here's my `.gitpod.yml` file so far:

```yaml
---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  # from https://www.gitpod.io/docs/languages/go#start-up-tasks
  - init: |
      go get -v github.com/go-delve/delve/cmd/dlv
      go get -v -t -d ./...
    command: |
      go build -o app && ./app

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
vscode:
  extensions:
    - golang.go
```

Note that I tried adding a step to run `go get -v github.com/go-delve/delve/cmd/dlv` but it didn't work. The details below explain how I concluded that this is the command I should try adding to get it to work.

Repo: https://github.com/mattwelke/go-starter

1. What version of Delve are you using (`dlv version`)?

Trying to install latest version.

2. What version of Go are you using? (`go version`)?

```
go version go1.17.3 linux/amd64
```

3. What operating system and processor architecture are you using?

Gitpod - Ubuntu

```
gitpod /workspace/pii-regex-test-go $ sudo lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

4. What did you do?

Used the following "init" task in my Gitpod config:

```
  - init: |
      go get -v github.com/go-delve/delve/cmd/dlv
      go get -v -t -d ./...
```

5. What did you expect to see?

Expected that after creating a new Gitpod workspace, I would be able to use the VS Code debugger immediately (so long as I did a Gitpod prebuild or waited until the init task had finished completing).

6. What did you see instead?

When a new workspace is opened, I see the following output in the terminal: https://gist.github.com/mattwelke/aca6feb12ba29de1bcbb1e2378bb3fca

I also see these popups in the lower right corner:

![image](https://user-images.githubusercontent.com/7719209/143622339-3dcaaf39-17de-417e-82a0-8279ca14b9cb.png)

When I open `main.go` and run the debugger, I see this error:

![image](https://user-images.githubusercontent.com/7719209/143622359-d7df803e-ae1f-4836-b330-db68403417f0.png)

If I click "Install", I see the following output in the OUTPUT tab for "Go":

```
Tools environment: GOPATH=/workspace/go
Installing 1 tool at /workspace/go/bin in module mode.
  dlv-dap

Installing github.com/go-delve/delve/cmd/dlv@master (/workspace/go/bin/dlv-dap) SUCCEEDED

All tools successfully installed. You are ready to Go. :)
```

If I then run the debugger, I see the following output in the DEBUG CONSOLE tab:

```
Starting: /workspace/go/bin/dlv-dap dap --check-go-version=false --listen=127.0.0.1:42375 --log-dest=3 from /workspace/go-starter
DAP server listening at: 127.0.0.1:42375
Type 'dlv help' for list of commands.
Hello, World!
Process 4078 has exited with status 0
Detaching
dlv dap (3350) exited with code: 0
```

This shows that after installing this tool, it works.

The line "Installing github.com/go-delve/delve/cmd/dlv@master" that I saw during the tool install output stood out to me as interesting. That's what led to me concluding I needed to install this tool in the init task to make sure my workspace had all the tools it needed to debug Go code right away. I was surprised to see that this didn't work.
