### ISSUE TITLE
freebsd-14-2 image is missing Go (lang/go) in pkg repository

### ISSUE THREAD

**Issue by codeaucafe** [go-delve/delve#3994]
## Summary

I noticed that the Cirrus test task always fails for `pkg: No packages available to install matching 'go' have been found in the repositories`. The `freebsd-14-2` image currently used in Cirrus CI does not include any version of Go (`lang/go`) in its pkg repository, making it impossible to install Go with `pkg install`, and thus the test task fails.

## Steps to Reproduce

Tweak existing `cirrus.yml` with the following Cirrus CI configuration:

```yaml
freebsd_instance:
  image_family: freebsd-14-2

test_task:
  install_script:
    - pkg update -f
    - pkg search ^go
    - pkg install -y go gcc git
```

## Expected Behavior

At least one version of Go (e.g., go122) should be available and installable via pkg install in order for tests to be run via Cirrus.

## Actual Behavior

pkg: No packages available to install matching 'go' have been found in the repositories

## Possible Workaround

```
fetch https://go.dev/dl/go1.22.1.freebsd-amd64.tar.gz
tar -C /usr/local -xzf go1.22.1.freebsd-amd64.tar.gz
export PATH="/usr/local/go/bin:$PATH"
```

I plan on fixing this, if that is fine with delve maintainers. I already have a branch (and draft PR - but currently thats mostly for debugging for this issue). I just need to add the possible workaround (or similar to install go. Will submit PR when ready.
